### ISSUE TITLE
Netlify deploy

### ISSUE THREAD

**Issue by yansusanto** [infantiablue/cryptocurrency-chart#1]
Perhaps this is not the issue related to the chart but I kinda failed to deploy it to netlify. Apparently, [the chart is not showing](https://ethchart.netlify.app/) .

Am I not sure what I'm missing but a tip or two is much appreciated.

Thank you.

**Comment by infantiablue** [comment]
have you checked console in your browser to see if any error happened ?

**Comment by alebreiz** [comment]
`Loading module from “https://ethchart.netlify.app/src/main.jsx” was blocked because of a disallowed MIME type (“application/octet-stream”)`

Am I missing something here?

**Comment by infantiablue** [comment]
I investigated your HTML source and found that you included the main.jsx directly. It should be built to .js bundle by using vite as in my tutorial.
